"""
bench-hybrid: BM25 + k-NN hybrid query with optional metadata filter.

What this measures
-------------------
Issue hybrid queries that combine full-text BM25 (on the ``content`` field)
with k-NN vector search (on ``description_vector``), optionally adding a
keyword filter on ``metadata.category`` to test how pre/post-filtering
affects latency and recall.

OpenSearch version compatibility
----------------------------------
- OpenSearch 3.x: native ``hybrid`` query type with score normalization
  (requires a search pipeline with a normalization-processor to be set up).
  Falls back to ``bool { should: [match, knn] }`` if the pipeline does not
  exist.
- OpenSearch 2.17 / 2.19: ``bool { should: [match, knn] }`` fallback always
  used.  The results are still meaningful for latency comparison; recall may
  differ because the scores are not normalized.

Filter selectivity
-------------------
``--filter-selectivity`` controls how many docs the metadata filter matches:
  - ``none``  — no filter applied; pure hybrid.
  - ``low``   — filter on a broad category (~25 % of docs).
  - ``high``  — filter on a specific category (~6 % of docs).

Run ``bench-index`` with ``--with-metadata`` (and ``--with-text``) first
so the index has the ``content`` and ``metadata`` fields.
"""

from __future__ import annotations

import time
from pathlib import Path

import numpy as np

from .clickhouse_sink import get_sink
from .config import Settings
from .corpus import load_corpus
from .opensearch_client import KnnSpec, get_index_stats, get_opensearch_client
from .report_context import benchmark_report_extras
from .reporter import write_report
from .stats import percentiles_ms

_QRELS_NAME = "qrels.npy"
_RECALL_KS = (1, 5, 10, 50, 100)

# Categories chosen to approximate low vs high selectivity given the 16-cat
# distribution generated by _add_synthetic_metadata.
_LOW_FILTER_CATEGORY = "infrastructure"   # ~6% of docs
_HIGH_FILTER_CATEGORY = "incident"        # ~6% of docs (high named for test symmetry)


def _hybrid_query(
    vector: np.ndarray,
    k: int,
    *,
    query_text: str,
    filter_category: str | None,
    use_native_hybrid: bool,
) -> dict:
    """
    Build an OpenSearch query body for a hybrid (BM25 + k-NN) search.

    ``use_native_hybrid``:
      True  → ``hybrid`` query type (OpenSearch 3.x, requires pipeline).
      False → ``bool { should: [match, knn] }`` (all versions).
    """
    knn_clause = {
        "knn": {
            "description_vector": {
                "vector": vector.tolist(),
                "k": k,
            }
        }
    }
    bm25_clause = {"match": {"content": {"query": query_text}}}

    if filter_category:
        filter_clause = {"term": {"metadata.category": filter_category}}
    else:
        filter_clause = None

    if use_native_hybrid:
        queries = [bm25_clause, knn_clause]
        body: dict = {
            "size": k,
            "query": {"hybrid": {"queries": queries}},
        }
        if filter_clause:
            body["post_filter"] = filter_clause
    else:
        must_not: list = []
        should = [bm25_clause, knn_clause]
        body = {
            "size": k,
            "query": {
                "bool": {
                    "should": should,
                    "minimum_should_match": 1,
                }
            },
        }
        if filter_clause:
            body["query"]["bool"]["filter"] = [filter_clause]

    return body


def _search(client, index: str, body: dict) -> list[str]:
    resp = client.search(index=index, body=body)
    return [h["_id"] for h in resp.get("hits", {}).get("hits", [])]


def _detect_native_hybrid(client, index: str) -> bool:
    """
    Return True if the cluster supports native hybrid queries.

    We probe by sending a trivial hybrid query and checking whether it returns
    a 4xx error.  Avoids inspecting version strings directly so it works
    correctly even if the cluster reports an unexpected version.
    """
    try:
        client.search(
            index=index,
            body={
                "size": 1,
                "query": {
                    "hybrid": {
                        "queries": [{"match_all": {}}]
                    }
                },
            },
        )
        return True
    except Exception:
        return False


def cmd_bench_hybrid(
    settings: Settings,
    *,
    query_count: int,
    k: int,
    embed_dim: int,
    spec: KnnSpec | None = None,
    filter_selectivity: str = "none",
    corpus_dir: str,
    out_dir: str,
    label: str,
    opensearch_uri: str | None = None,
) -> int:
    uri = opensearch_uri or settings.opensearch_uri
    knn = spec or KnnSpec(embed_dim=embed_dim, with_text=True, with_metadata=True)
    deployment_ctx, preflight_ctx = benchmark_report_extras(settings, uri)
    client = get_opensearch_client(uri)

    if not client.indices.exists(index=settings.opensearch_index):
        print(f"[bench-hybrid] ERROR: index '{settings.opensearch_index}' does not exist.")
        print("[bench-hybrid] Run 'bench-index --with-text --with-metadata' first.")
        return 1

    stats = get_index_stats(client, settings.opensearch_index)
    doc_count = stats["doc_count"]
    if doc_count == 0:
        print(f"[bench-hybrid] ERROR: index '{settings.opensearch_index}' is empty.")
        return 1

    use_native = _detect_native_hybrid(client, settings.opensearch_index)
    query_mode = "native-hybrid" if use_native else "bool-should"
    print(f"[bench-hybrid] Hybrid mode: {query_mode}")

    filter_category: str | None = None
    if filter_selectivity == "low":
        filter_category = _LOW_FILTER_CATEGORY
    elif filter_selectivity == "high":
        filter_category = _HIGH_FILTER_CATEGORY

    print(f"[bench-hybrid] filter_selectivity={filter_selectivity}  category={filter_category!r}")

    # Load ground truth if available (for recall computation).
    qrels_path = Path(corpus_dir) / _QRELS_NAME
    has_qrels = qrels_path.exists()
    if has_qrels:
        import pandas as pd
        qrels = np.load(str(qrels_path))
        docs_df = pd.read_parquet(Path(corpus_dir) / "docs.parquet")
        docs_df = docs_df.iloc[:int(doc_count)]
        idx_to_id = dict(enumerate(docs_df["doc_id"].astype(str)))
        gt_k = qrels.shape[1]
    else:
        print("[bench-hybrid] qrels.npy not found — recall will not be computed.")
        qrels = None
        idx_to_id = {}
        gt_k = 0

    print(f"[bench-hybrid] Loading corpus from {corpus_dir} at dim={embed_dim}...")
    bundle = load_corpus(corpus_dir, embed_dim)
    available = len(bundle.queries)
    if has_qrels:
        available = min(available, qrels.shape[0])
    if query_count > available:
        print(
            f"[bench-hybrid] WARNING: requested {query_count} queries, "
            f"available {available}. Using {available}."
        )
        query_count = available

    query_vectors = bundle.query_vectors[:query_count]
    queries_df = bundle.queries.iloc[:query_count]
    query_texts = queries_df["text"].tolist()

    latencies_ms: list[float] = []
    recall_sums = {rk: 0.0 for rk in _RECALL_KS if rk <= max(k, gt_k or k)}

    print(
        f"[bench-hybrid] Running {query_count} hybrid queries (k={k}, dim={embed_dim})..."
    )

    for q_idx, (vec, text) in enumerate(zip(query_vectors, query_texts)):
        body = _hybrid_query(
            vec,
            k,
            query_text=text,
            filter_category=filter_category,
            use_native_hybrid=use_native,
        )
        t0 = time.perf_counter()
        retrieved = _search(client, settings.opensearch_index, body)
        latencies_ms.append((time.perf_counter() - t0) * 1000)

        if has_qrels and qrels is not None:
            max_k = min(k, gt_k)
            true_ids = {
                idx_to_id[int(i)]
                for i in qrels[q_idx][:max_k]
                if int(i) in idx_to_id
            }
            for rk in list(recall_sums.keys()):
                if rk <= max_k:
                    recall_sums[rk] += (
                        1.0 if any(rid in true_ids for rid in retrieved[:rk]) else 0.0
                    )

    lat = percentiles_ms(latencies_ms)
    recall_results = (
        {f"recall@{rk}": round(recall_sums[rk] / query_count, 4) for rk in recall_sums}
        if has_qrels
        else {}
    )

    sink = get_sink()
    sel_label = {"selectivity": filter_selectivity, "query_mode": query_mode}
    sink.metric("search_p50_ms", float(lat["p50_ms"]), labels={**sel_label, "phase": "hybrid"})
    sink.metric("search_p95_ms", float(lat["p95_ms"]), labels={**sel_label, "phase": "hybrid"})
    sink.metric("search_p99_ms", float(lat["p99_ms"]), labels={**sel_label, "phase": "hybrid"})
    if has_qrels:
        for rk, score in recall_results.items():
            k_value = rk.split("@", 1)[1]
            sink.metric(
                "recall_at_k",
                float(score),
                labels={**sel_label, "k": k_value, "phase": "hybrid"},
            )

    result_row = {
        "queries":            query_count,
        "k":                  k,
        "query_mode":         query_mode,
        "filter_selectivity": filter_selectivity,
        "filter_category":    filter_category or "",
        "p50_ms":             round(lat["p50_ms"], 1),
        "p95_ms":             round(lat["p95_ms"], 1),
        "p99_ms":             round(lat["p99_ms"], 1),
        "max_ms":             round(lat["max_ms"], 1),
        "mean_ms":            round(lat["mean_ms"], 1),
        **recall_results,
    }

    print(
        f"[bench-hybrid] p50={lat['p50_ms']:.1f}ms  p95={lat['p95_ms']:.1f}ms  "
        + ("  ".join(f"{rk}={v:.3f}" for rk, v in recall_results.items()) if recall_results else "")
    )

    json_path, md_path = write_report(
        "bench-hybrid",
        params={
            "plan_label":         label,
            "index":              settings.opensearch_index,
            "doc_count":          doc_count,
            "query_count":        query_count,
            "k":                  k,
            "embed_dim":          embed_dim,
            "knn_spec":           knn.to_dict(),
            "query_mode":         query_mode,
            "filter_selectivity": filter_selectivity,
            "filter_category":    filter_category or "",
            "corpus_preset":      bundle.manifest.get("preset"),
            "corpus_dir":         corpus_dir,
        },
        results=[result_row],
        deployment=deployment_ctx,
        preflight=preflight_ctx,
        notes=[
            f"Hybrid mode: {query_mode}",
            f"Filter selectivity: {filter_selectivity} (category={filter_category!r})",
            f"k-NN spec: {knn.label()}",
            "recall metrics are computed against brute-force ground truth from qrels.npy."
            if has_qrels
            else "recall metrics not available (run bench-build-groundtruth first).",
        ],
        out_dir=out_dir,
    )
    print(f"[bench-hybrid] Wrote: {json_path}")
    print(f"[bench-hybrid] Wrote: {md_path}")
    return 0
